Puddle/core/urls.py
from django.urls import path
from . import views

app_name='core'

urlpatterns=[
    path('',views.index,name='index'),
    path('contact/',views.contact,name='contact'),
    path('signup/',views.signup,name='signup'),
]

Puddle/item/urls.py
from django.urls import path
from . import views

app_name='item'
urlpatterns=[
    path('<int:pk>/',views.detail,name='detail'),
]

Puddle/puddle/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('items/',include('item.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Puddle/core/models.py
from django.db import models

# Create your models here.

Puddle/item/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=255)

    class Meta:
        ordering=('name',)
        verbose_name_plural='Categories'
    def __str__(self):
        return self.name    

class Item(models.Model):
    category=models.ForeignKey(Category,related_name='items',on_delete=models.CASCADE)
    name=models.CharField(max_length=255)
    description=models.TextField(blank=True,null=True)
    price=models.FloatField()
    image=models.ImageField(upload_to='item_images',blank=True,null=True)
    is_sold=models.BooleanField(default=False)
    created_by=models.ForeignKey(User,related_name='items',on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name  

Puddle/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model=User
        field=('username','email','password1','password2')
        widgets={
            'username':forms.TextInput(attrs={
                'placeholder':'Your username',
                'class':'w-full py-4 px-6 rounded-xl'
        }),
        'email':forms.EmailInput(attrs={
                'placeholder':'Your email address',
                'class':'w-full py-4 px-6 rounded-xl'
        }),
        'password1':forms.PasswordInput(attrs={
                'placeholder':'Your password',
                'class':'w-full py-4 px-6 rounded-xl'
        }),
        'password2':forms.PasswordInput(attrs={
                'placeholder':'Repeat password',
                'class':'w-full py-4 px-6 rounded-xl'
        })

        }
        username=forms.CharField(widget=forms.TextInput(attrs={
            'placeholder':'Your username',
            'class':'w-full py-4 px-6 rounded-xl'
        }))
        email=forms.EmailField(widget=forms.TextInput(attrs={
            'placeholder':'Your email address',
            'class':'w-full py-4 px-6 rounded-xl'
        }))
        password1=forms.CharField(widget=forms.TextInput(attrs={
            'placeholder':'Your username',
            'class':'w-full py-4 px-6 rounded-xl'
        }))

Puddle/core/views.py
from django.shortcuts import render,redirect
from item.models import Category,Item
from .forms import SignUpForm

# Create your views here.
def index(request):
    items=Item.objects.filter(is_sold=False)[0:6]
    categories=Category.objects.all()
    context={
        'categories':categories,
        'items':items,
    }
    return render(request,'index.html',context)

def contact(request):
    return render(request,'contact.html')

def signup(request):
    if request.method=='POST':
        form=SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login')
    else:
        form=SignUpForm()
    return render(request,'signup.html',{
        'form':form
    })

Puddle/item/views.py
from django.shortcuts import render,get_object_or_404
from .models import Item

# Create your views here.
def detail(request,pk):
    item=get_object_or_404(Item,pk=pk)
    related_items=Item.objects.filter(category=item.category,is_sold=False).exclude(pk=pk)[0:3]
    return render(request,'detail.html',
                  {'item':item,
                   'related_items':related_items})

Puddle/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %}| Puddle</title>
  </head>
  <body>
    <nav
      class="py-6 px-6 flex justify-between items-center border-b border-gray-200"
    >
      <a href="/" class="text-xl font-semibold">Puddle</a>
      <div class="space-x-6">
        <a href="#" class="text-lg font-semibold hover:text-gray-500"
          >New item</a
        >
        <a href="#" class="text-lg font-semibold hover:text-gray-500">Browse</a>

        <a
          href="{% url 'signup' %}"
          class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700"
          >Sign up</a
        >
        <a
          href="#"
          class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700"
          >Log in</a
        >
      </div>
    </nav>
    <div class="px-6 py-6">{% block content %} {% endblock %}</div>
    <footer class="py-6 px-6 flex justify-between bg-gray-800">
      <div class="w-2/3 pr-10">
        <h3 class="mb-5 font-semibold text-gray-400">About</h3>
        <p class="text-lg text-gray-500">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt qui
          labore adipisci, aspernatur ex error ipsum voluptates nesciunt dolores
          consequatur enim blanditiis nobis recusandae, laboriosam quo fugiat
          aut! Consequuntur, inventore!
        </p>
      </div>
      <div class="w-1/3">
        <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
        <ul class="space-y-2">
          <li>
            <a href="#" class="text-lg text-teal-500 hover:text-teak-700"
              >About</a
            >
          </li>
          <li>
            <a
              href="{% url 'contact' %}"
              class="text-lg text-teal-500 hover:text-teak-700"
              >Contact</a
            >
          </li>
          <li>
            <a href="#" class="text-lg text-teal-500 hover:text-teak-700"
              >Privacy policy</a
            >
          </li>
          <li>
            <a href="#" class="text-lg text-teal-500 hover:text-teak-700"
              >Terms of Use</a
            >
          </li>
        </ul>
      </div>
    </footer>
  </body>
</html>

Puddle/templates/contact.html
{% extends 'base.html' %} <br />
{% block title %}Contact{% endblock %} {% block content%}
<h1>The contact page</h1>
{% endblock %}

Puddle/templates/detail.html
{% extends 'base.html' %} <br />
{% block title %}{{ item.name }}{% endblock %} <br />
{%block content %}
<div class="grid grid-cols-5 gap-6">
  <div class="col-span-3">
    <img src="{{ item.image.url }}" class="rounded-xl" />
  </div>

  <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
    <p class="text-gray-500"><strong>Price: </strong>{{ item.price }}</p>
    <p class="text-gray-500">
      <strong>Seller: </strong>{{ item.created_by.username }}
    </p>

    {% if item.description %}
    <p class="text-gray-700">
      <strong class="text-gray-500">Description:</strong><br />
      {{ item.description }}
    </p>
    {% endif %} {% if request.user == item.created_by %}
    <div class="mt-6 p-6 bg-white rounded-xl">
      <p>This is your item!</p>

      <a
        href="{% url 'item:edit' item.id %}"
        class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl"
        >Edit</a
      >
      <a
        href="{% url 'item:delete' item.id %}"
        class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl"
        >Delete</a
      >
    </div>
    {% else %}
    <a
      href="{% url 'conversation:new' item.id %}"
      class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700"
      >Contact seller</a
    >
    {% endif %}
  </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
  <h2 class="mb-12 text-2xl text-center">Related items</h2>

  <div class="grid grid-cols-3 gap-3">
    {% for item in related_items %}
    <div>
      <a href="{% url 'item:detail' item.id %}">
        <div>
          <img src="{{ item.image.url }}" class="rounded-t-xl" />
        </div>

        <div class="p-6 bg-white rounded-b-xl">
          <h2 class="text-2xl">{{ item.name }}</h2>
          <p class="text-gray-500">Price: {{ item.price }}</p>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

Puddle/templates/index.html
{% extends 'base.html' %} <br />
{% block title %}Welcome{% endblock %} {% block content%}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
  <h2 class="mb-12 text-2xl text-center">Newest Items</h2>
  <div class="grid grid-cols-3 gap-3">
    {% for item in items %}
    <div>
      <a href="{% url 'item:detail' item.id %}">
        <div>
          <img src="{{ item.image.url }}" class="rounded-t-xl" />
        </div>
        <div class="p-6 bg-white rounded-b-xl">
          <h2 class="text-2xl">{{ item.name }}</h2>
          <p class="text-gray-500">Price:{{ item.price }}</p>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
  <h2 class="mb-12 text-2xl text-center">Categories</h2>
  <div class="grid grid-cols-3 gap-3">
    {% for category in categories %}
    <div>
      <a href="#">
        <div class="p-6 bg-white rounded-b-xl">
          <h2 class="text-2xl">{{ category.name }}</h2>
          <p class="text-gray-500">Price:{{ category.items.count }}</p>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

Puddle/templates/signup.html
{% extends base.html %} <br />
{% block title %}Sign up{% endblock %} {% block content%}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
  <h1 class="mb-6 text-3xl">Sign up</h1>
  <form method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label class="inline-block mb-2">Username</label> <br />
      {{ form.username }}
    </div>
    <div class="mb-3">
      <label class="inline-block mb-2">Email</label> <br />
      {{ form.email }}
    </div>
    <div class="mb-3">
      <label class="inline-block mb-2">Password1</label> <br />
      {{ form.password1 }}
    </div>
    <div class="mb-3">
      <label class="inline-block mb-2">Repeat password</label> <br />
      {{ form.password2 }}
    </div>
    {% if form.errors or form.non_field_errors %}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
      {% for field in form %} {{field.errors}} {% endfor %}
      <br />
      {{ form.non_field_errors }}
    </div>
    <button
      class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white"
    >
      Submit
    </button>
  </form>
</div>
{% endblock %}